[build]
  base = "VISUAL SEARCH"
  command = "npm run build"
  publish = "VISUAL SEARCH/.next"

[build.environment]
  NEXT_USE_SENTRY = "false"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
